using System.Globalization;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using VoltGuard.Application.DTOs.Reports;

namespace VoltGuard.Infrastructure.Reports;

public class TestResultPdfDocument : IDocument
{
    private readonly TestResultReportDto _report;

    public TestResultPdfDocument(TestResultReportDto report)
    {
        _report = report;
    }

    public DocumentMetadata GetMetadata()
    {
        return new DocumentMetadata
        {
            Title = "VoltGuard Test Report",
            Author = "VoltGuard FieldLink",
            Subject = $"Test Result Report {GetCleanReportNumber()}",
            Keywords = "VoltGuard, TestResult, Electrical Test Report"
        };
    }

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(30);
            page.PageColor(Colors.White);
            page.DefaultTextStyle(x => x.FontSize(9).FontFamily("Arial"));

            page.Header().Element(ComposeHeader);

            page.Content()
                .PaddingTop(10)
                .Column(column =>
                {
                    column.Spacing(10);

                    column.Item().Element(ComposeStatusSummary);

                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Element(ComposeCustomerSection);
                        row.ConstantItem(12).Text("");
                        row.RelativeItem().Element(ComposeSiteSection);
                    });

                    column.Item().Element(ComposeAssetSection);
                    column.Item().Element(ComposeTestResultSection);
                    column.Item().Element(ComposeMeasurementsSection);
                    column.Item().Element(ComposeNotesSection);
                });

            page.Footer()
                .AlignCenter()
                .Text(text =>
                {
                    text.Span("Generated by VoltGuard FieldLink | Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                });
        });
    }

    private void ComposeHeader(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column.Item().Text("VoltGuard FieldLink")
                    .Bold()
                    .FontSize(18);

                column.Item().Text("Professional Electrical Test Report")
                    .FontSize(10);
            });

            row.ConstantItem(190).AlignRight().Column(column =>
            {
                column.Item().AlignRight().Text($"Generated: {FormatDateTime(_report.GeneratedAtUtc)}");
                column.Item().AlignRight().Text($"Report No: {GetCleanReportNumber()}");
            });
        });
    }

    private void ComposeStatusSummary(IContainer container)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(10)
            .Column(column =>
            {
                column.Spacing(5);

                column.Item().Row(row =>
                {
                    row.RelativeItem().Text(text =>
                    {
                        text.Span("Test Reference: ").SemiBold();
                        text.Span(Display(_report.TestReference));
                    });

                    row.RelativeItem().AlignRight().Text(text =>
                    {
                        text.Span("Test Date: ").SemiBold();
                        text.Span(FormatDateTime(_report.TestDateUtc));
                    });
                });

                column.Item().Row(row =>
                {
                    row.RelativeItem().Text(text =>
                    {
                        text.Span("Overall Status: ").SemiBold();
                        text.Span(Display(_report.OverallStatus)).Bold();
                    });

                    row.RelativeItem().Text(text =>
                    {
                        text.Span("Risk Level: ").SemiBold();
                        text.Span(DisplayRisk(_report.RiskLevel)).Bold();
                    });

                    row.RelativeItem().Text(text =>
                    {
                        text.Span("Engineer: ").SemiBold();
                        text.Span(Display(_report.EngineerName));
                    });
                });
            });
    }

    private void ComposeCustomerSection(IContainer container)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8)
            .Column(column =>
            {
                column.Spacing(3);
                AddSectionTitle(column, "Customer");
                AddLine(column, "Name", _report.Customer.Name);
                AddLine(column, "Contact", _report.Customer.ContactPerson);
                AddLine(column, "Email", _report.Customer.ContactEmail);
                AddLine(column, "Phone", _report.Customer.ContactPhone);
                AddLine(column, "Address", BuildAddress(
                    _report.Customer.AddressLine1,
                    _report.Customer.AddressLine2,
                    _report.Customer.City,
                    _report.Customer.Postcode,
                    _report.Customer.Country));
            });
    }

    private void ComposeSiteSection(IContainer container)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8)
            .Column(column =>
            {
                column.Spacing(3);
                AddSectionTitle(column, "Site");
                AddLine(column, "Name", _report.Site.Name);
                AddLine(column, "Code", _report.Site.SiteCode);
                AddLine(column, "Type", _report.Site.SiteType);
                AddLine(column, "Contact", _report.Site.ContactPerson);
                AddLine(column, "Email", _report.Site.ContactEmail);
                AddLine(column, "Phone", _report.Site.ContactPhone);
                AddLine(column, "Address", BuildAddress(
                    _report.Site.AddressLine1,
                    _report.Site.AddressLine2,
                    _report.Site.City,
                    _report.Site.Postcode,
                    _report.Site.Country));
            });
    }

    private void ComposeAssetSection(IContainer container)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8)
            .Column(column =>
            {
                column.Spacing(3);
                AddSectionTitle(column, "Asset Details");

                column.Item().Row(row =>
                {
                    row.RelativeItem().Column(left =>
                    {
                        AddLine(left, "Name", _report.Asset.Name);
                        AddLine(left, "Asset Tag", _report.Asset.AssetTag);
                        AddLine(left, "Serial Number", _report.Asset.SerialNumber);
                        AddLine(left, "Asset Type", _report.Asset.AssetType);
                        AddLine(left, "Location", _report.Asset.LocationDescription);
                    });

                    row.RelativeItem().Column(right =>
                    {
                        AddLine(right, "Manufacturer", _report.Asset.Manufacturer);
                        AddLine(right, "Model", _report.Asset.Model);
                        AddLine(right, "Rated Voltage", FormatDecimalWithUnit(_report.Asset.RatedVoltage, "V"));
                        AddLine(right, "Rated Current", FormatDecimalWithUnit(_report.Asset.RatedCurrent, "A"));

                        if (IsKnown(_report.Asset.RiskLevel))
                        {
                            AddLine(right, "Current Asset Risk", _report.Asset.RiskLevel);
                        }
                    });
                });
            });
    }

    private void ComposeTestResultSection(IContainer container)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8)
            .Column(column =>
            {
                column.Spacing(3);
                AddSectionTitle(column, "Test Result Details");

                column.Item().Row(row =>
                {
                    row.RelativeItem().Column(left =>
                    {
                        AddLine(left, "Test Type", _report.TestType);
                        AddLine(left, "Test Date", FormatDateTime(_report.TestDateUtc));
                        AddLine(left, "Engineer", _report.EngineerName);
                        AddLine(left, "Next Test Due", FormatNullableDateTime(_report.NextTestDueAtUtc));
                    });

                    row.RelativeItem().Column(right =>
                    {
                        AddLine(right, "Instrument Model", _report.InstrumentModel);
                        AddLine(right, "Instrument Serial", _report.InstrumentSerialNumber);
                        AddLine(right, "Created", FormatDateTime(_report.CreatedAtUtc));
                        AddLine(right, "Updated", FormatNullableDateTime(_report.UpdatedAtUtc));
                    });
                });

                AddLine(column, "Summary", _report.Summary);
            });
    }

    private void ComposeMeasurementsSection(IContainer container)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8)
            .Column(column =>
            {
                column.Spacing(5);
                AddSectionTitle(column, "Measurements");

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(2);
                        columns.RelativeColumn(1);
                        columns.RelativeColumn(1.3f);
                        columns.RelativeColumn(2.2f);
                        columns.RelativeColumn(1.1f);
                        columns.RelativeColumn(1.2f);
                    });

                    table.Header(header =>
                    {
                        header.Cell().Element(HeaderCell).Text("Type");
                        header.Cell().Element(HeaderCell).Text("Phase");
                        header.Cell().Element(HeaderCell).Text("Value");
                        header.Cell().Element(HeaderCell).Text("Limits");
                        header.Cell().Element(HeaderCell).Text("Status");
                        header.Cell().Element(HeaderCell).Text("Critical");
                    });

                    foreach (var measurement in _report.Measurements
                        .OrderBy(x => x.DisplayOrder)
                        .ThenBy(x => x.MeasurementType))
                    {
                        table.Cell().Element(BodyCell).Text(Display(measurement.MeasurementType));
                        table.Cell().Element(BodyCell).Text(Display(measurement.Phase));
                        table.Cell().Element(BodyCell).Text($"{FormatDecimal(measurement.Value)} {Display(measurement.Unit)}");
                        table.Cell().Element(BodyCell).Text(BuildThresholdText(measurement));
                        table.Cell().Element(BodyCell).Text(Display(measurement.Status));
                        table.Cell().Element(BodyCell).Text(measurement.IsCritical ? "Yes" : "No");
                    }
                });

                var measurementNotes = _report.Measurements
                    .Where(x => !string.IsNullOrWhiteSpace(x.Notes))
                    .OrderBy(x => x.DisplayOrder)
                    .ThenBy(x => x.MeasurementType)
                    .ToList();

                if (measurementNotes.Any())
                {
                    column.Item().PaddingTop(6).Text("Measurement Notes").SemiBold();

                    foreach (var measurement in measurementNotes)
                    {
                        column.Item().Text(text =>
                        {
                            text.Span($"{measurement.MeasurementType}: ").SemiBold();
                            text.Span(Display(measurement.Notes));
                        });
                    }
                }
            });
    }

    private void ComposeNotesSection(IContainer container)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8)
            .Column(column =>
            {
                column.Spacing(3);
                AddSectionTitle(column, "Notes");
                AddLine(column, "Test Notes", _report.Notes);
                AddLine(column, "Asset Notes", _report.Asset.Notes);
                AddLine(column, "Site Notes", _report.Site.Notes);
                AddLine(column, "Customer Notes", _report.Customer.Notes);

                column.Item()
                    .PaddingTop(6)
                    .Text("This report is system-generated from VoltGuard FieldLink data.")
                    .Italic()
                    .FontSize(8);
            });
    }

    private string GetCleanReportNumber()
    {
        if (!string.IsNullOrWhiteSpace(_report.TestReference))
        {
            return _report.TestReference.Trim();
        }

        return $"VG-TR-{_report.TestDateUtc:yyyyMMdd}-{_report.TestResultId.ToString("N")[..8].ToUpperInvariant()}";
    }

    private static IContainer HeaderCell(IContainer container)
    {
        return container
            .Background(Colors.Grey.Lighten3)
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(4);
    }

    private static IContainer BodyCell(IContainer container)
    {
        return container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(4);
    }

    private static void AddSectionTitle(ColumnDescriptor column, string title)
    {
        column.Item().Text(title).Bold().FontSize(11);
        column.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
    }

    private static void AddLine(ColumnDescriptor column, string label, string? value)
    {
        column.Item().Text(text =>
        {
            text.Span($"{label}: ").SemiBold();
            text.Span(Display(value));
        });
    }

    private static string Display(string? value)
    {
        return string.IsNullOrWhiteSpace(value) ? "-" : value.Trim();
    }

    private static string DisplayRisk(string? value)
    {
        return IsKnown(value) ? value!.Trim() : "Not assessed";
    }

    private static bool IsKnown(string? value)
    {
        return !string.IsNullOrWhiteSpace(value)
            && !string.Equals(value.Trim(), "Unknown", StringComparison.OrdinalIgnoreCase);
    }

    private static string FormatDateTime(DateTime value)
    {
        return value.ToString("yyyy-MM-dd HH:mm 'UTC'", CultureInfo.InvariantCulture);
    }

    private static string FormatNullableDateTime(DateTime? value)
    {
        return value.HasValue ? FormatDateTime(value.Value) : "-";
    }

    private static string FormatDecimal(decimal value)
    {
        return value.ToString("0.####", CultureInfo.InvariantCulture);
    }

    private static string FormatDecimalWithUnit(decimal? value, string unit)
    {
        return value.HasValue ? $"{FormatDecimal(value.Value)} {unit}" : "-";
    }

    private static string BuildThresholdText(ReportMeasurementDto measurement)
    {
        var parts = new List<string>();

        var allowed = BuildRangeText(
            "Allowed",
            measurement.MinimumAllowedValue,
            measurement.MaximumAllowedValue);

        if (!string.IsNullOrWhiteSpace(allowed))
        {
            parts.Add(allowed);
        }

        var warning = BuildRangeText(
            "Preferred",
            measurement.WarningMinimumValue,
            measurement.WarningMaximumValue);

        if (!string.IsNullOrWhiteSpace(warning))
        {
            parts.Add(warning);
        }

        return parts.Count == 0 ? "No limits set" : string.Join("; ", parts);
    }

    private static string? BuildRangeText(string label, decimal? minimum, decimal? maximum)
    {
        if (minimum.HasValue && maximum.HasValue)
        {
            return $"{label}: {FormatDecimal(minimum.Value)} - {FormatDecimal(maximum.Value)}";
        }

        if (minimum.HasValue)
        {
            return $"{label}: >= {FormatDecimal(minimum.Value)}";
        }

        if (maximum.HasValue)
        {
            return $"{label}: <= {FormatDecimal(maximum.Value)}";
        }

        return null;
    }

    private static string BuildAddress(params string?[] parts)
    {
        var address = string.Join(", ", parts
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => x!.Trim()));

        return string.IsNullOrWhiteSpace(address) ? "-" : address;
    }
}
